### ISSUE TITLE
Assertion failed in build.cpp

### ISSUE THREAD

**Issue by bcollins526** [zeux/qgrep#12]
I get

Assertion failed: context->pendingSize == 0 && context->pendingFiles.empty(), file C:\Users\brianc\projects\tools\external\qgrep\src\build.cpp, line 678

when I run qgrep update <myproject>

I've been using this for about a month, no problems until now. Anything obvious I can look for, or check? Thanks,

**Comment by zeux** [comment]
I think what might be going on is that there's a zero-length file and the logic in `buildAppendChunk` doesn't account for that.

Do you get this every time you run `qgrep update`? If so, would you mind changing the condition in `buildAppendChunk` at line 659 to 

```
	if (!context->pendingFiles.empty())
```

And trying again?

**Comment by bcollins526** [comment]
Yes, it happens every time I run qgrep. I changed that logic, rebuilt, ensured I was running the new executable, but unfortunately, I still get the (same) assert. If you have other ideas, just let me know, since I'm set up to build again now.

**Comment by zeux** [comment]
Hmm, this is odd. Would you mind printing the pending size and files before the assertion, and checking if any of the pending files are indeed zero-length? I can try to reproduce this myself if that's the case.

**Comment by zeux** [comment]
(worth noting is that I suspect that you can get out of this situation using `qgrep build project` once, which is a non-incremental build; I can try to figure out what the problem is separately)

**Comment by bcollins526** [comment]
```
pending size: 0
pending file: C:/Users/bcollins/AppData/Local/Microsoft/F12/header/MyCode.json
pending file: C:/Users/bcollins/AppData/Local/Microsoft/F12/network/settings.json
pending file: C:/Users/bcollins/AppData/Local/Microsoft/F12/perftools/memory/settings.json
pending file: C:/Users/bcollins/AppData/Local/Microsoft/F12/perftools/visualprofiler/settings.json
Assertion failed: context->pendingSize == 0 && context->pendingFiles.empty(), file C:\Users\bcollins\projects\tools\external\qgrep\src\build.cpp, line 684
```
ok pending size appears to be 0, but it's always those same 4 files... also, they are all identical (diff yields no differences) and of size 197121. weird.

**Comment by bcollins526** [comment]
ah this is some weird juju, the files are actually empty!

**Comment by bcollins526** [comment]
![image](https://user-images.githubusercontent.com/60075820/80048880-50ab0e00-84c6-11ea-9dc9-5f3167a69eec.png)

**Comment by zeux** [comment]
I'm going to have to adjust this logic because it's not just empty files that might be the problem, there's other subtle issues in the split code that can perform suboptimal decisions.

If `qgrep build` doesn't solve the problem, you should be able to replace the assertion with something like `if (!context->pendingFiles.empty()) return false;` - I will work on a PR that hopefully can make this more robust.

**Comment by bcollins526** [comment]
Thanks for the workaround. I made a temporary project I can use for the time being, so I don't lose the test case that led to this, since I don't really know how to reproduce it.

**Comment by zeux** [comment]
I'm still testing the fix to make sure that it keeps a reasonable distribution of chunk sizes but I think this should fix the problem you were running into 🤞

**Comment by bcollins526** [comment]
Fix worked, qgrep update no longer asserts. Thank you!
