### ISSUE TITLE
Error reading .cfg file

### ISSUE THREAD

**Issue by datainstigator** [zeux/qgrep#28]
Hi I have an issue on Linux, trying to create db files in an alternative directory 
(system drive is 250gb nvme, so ~/.qgrep is no good for large datasets).

I specify the init and update commands with explicit pathways instead of a project name, as suggested in README.md.
Files are indexed/created, it seems to run without issue.

When trying to run a search (again using explicit pathway to .cfg file), I get error "Unable to read file.cfg".

I have created test directories on mounted internal drives, set permissions to 777 for pathway and all files to rule out permissions.

Are you able to replicate this?

**Comment by zeux** [comment]
Seems to work fine for me. Note that you need to specify the file path as relative (starting with `./`) or absolute (starting with `/`) - this is consistent between different commands, so eg

```
qgrep init ./file.cfg folder
qgrep update ./file.cfg
qgrep search ./file.cfg term
```

should work.

**Comment by datainstigator** [comment]
Hi thank you for responding - and, also thank you for an amazing app, after trying multiple commercial tools, I came across yours and it's proven the potential to be a fantastic fix for me, once I iron out this issue - really nice work... :)

Interesting. I am specifying absolute paths.

I wonder - I downloaded the ubuntu performance release zip, so I have to do 'dot slash qgrep':

./qgrep init /mnt/etc.

...whereas you don't. 

> Maybe this is because you've compiled/installed and I haven't? 
> If so, which version of Ubuntu are you running, and how did you install? (when I tried to do git clone and run 'make' command, I got a gcc error about a missing file, which is why tried downloading the quick release zip).

**Comment by zeux** [comment]
I was actually using `./qgrep`, I simplified above. Can you post the full command line and the error message?

**Comment by datainstigator** [comment]
Apologies for delay - vacation. 

My commands are the same as yours.

Curious, I noticed that the cfg file was being appended with an underscore, which is why it errored. file.cfg_ was being created, which caused the error. I've rebuilt my system (needed doing anyway), and it seems to be working just fine now :-/
