### ISSUE TITLE
How to compile qgrep on Linux Ubuntu / macOS ?

### ISSUE THREAD

**Issue by Zabrane** [zeux/qgrep#37]
Hi @zeux 
Would you mind expanding the doc explaining how to compile `qgrep`?
Many thanks

**Comment by zeux** [comment]
It's just `make`; the repository uses submodules so it needs to be cloned with `--recursive`. Binaries are also available in https://github.com/zeux/qgrep/releases/tag/v1.4. I'll add this to the doc.

**Comment by Zabrane** [comment]
Thanks a lot @zeux
