### ISSUE TITLE
qgrep search results displays files with paths containing backslashes in Linux (instead of slashes)

### ISSUE THREAD

**Issue by livghe** [zeux/qgrep#8]
Summary:
I am using qgrep (build be me from sources on github) on Linux CentOS, and in the search results I see back-slashes instead of slashes in file paths (those files where the matches occur)

Test steps:
root@DevMachine:/opt/devenv/projects# qgrep search tos Vl "xsl.cgi"
\opt\devenv\project\build.shinobi(465):  "xsl.cgi":{"files":"cgi/xsl/*.cc",
\opt\devenv\project\build.shinobi.old(453):  "xsl.cgi":{"files":"cgi/xsl/*.cc",
\opt\devenv\project\deploy_new_sdk.sh(9): pkill xsl.cgi
\opt\devenv\project\deploy_old_sdk.sh(25):pkill xsl.cgi
\opt\devenv\project\stinst.spec(167):cp ${STPUB}/${OPT}/xsl.cgi ${RPM_BUILD_ROOT}/var/www/cgi-bin
\opt\devenv\project\stinst.spec(2503):/var/www/cgi-bin/xsl.cgi

Expected result:
Files in the search result should contain paths separated by "/", and not "\", since I am on Linux, not Windows, so it makes it impossible for me to open that file in Vim for instance, without first replacing all "\" with "/".
So, the output should be like:
/opt/devenv/project/build.shinobi(465):  "xsl.cgi":{"files":"cgi/xsl/*.cc"

qgrep should find out on which platform it runs, and display the paths according to this.

**Comment by livghe** [comment]
I don't need the "V" option on Linux. I used qgrep on Windows with VS, and now I switched to Linux, so I was used to those search options.

If this is the intended behavior for "V", we can close this issue then.
But I am wondering if there are any other IDE's for Linux (like CodeBlocks, Codelite, etc) that accept the search results like VS (with the line number between parenthesis), because in this case qgrep might not integrate well with those in Linux.

**Comment by zeux** [comment]
Ok, that makes sense. OTOH I believe IDEs for Linux are likely to be compatible with the default output format qgrep uses since it matches gcc/clang error reporting on these platforms, as well as grep tool itself. So for now I'll assume Visual-Studio style output with forward slashes is not useful and close this.
